[package]
name = "aoc-cryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-iter-tools = { path = "../aoc-iter-tools" }